language: java
jdk: oraclejdk7
branches:
  only:
    - master
cache:
  directories:
    - $yiruhu/ser515UnitTest/SortingGiven/SortingGiven/.gradle


before_cache:
  - rm -f  $yiruhu/ser515UnitTest/SortingGiven/SortingGiven/.gradle
  - rm -fr $yiruhu/ser515UnitTest/SortingGiven/SortingGiven/.gradle

