language: java
jdk: oraclejdk7
branches:
  only:
    - master
cache:
  directories:
    - $HOME/ser515UnitTest/SortingGiven/SortingGiven/.gradle
before_script:
  - git fetch
  - git checkout -b gh-pages
  - git merge origin/master
  - git rm --cached --ignore-unmatch index.html
  
script:
  - ./gradlew clean publish -i --continue
  - ./gradlew -b finalize.gradle finalize -i

before_cache:
  - rm -f  $HOME/ser515UnitTest/SortingGiven/SortingGiven/.gradle
  - rm -fr $HOME/ser515UnitTest/SortingGiven/SortingGiven/.gradle

